version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
    restart: always
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5001:5000"
    depends_on:
      - db
    restart: on-failure